networks:
  t-network:
    driver: bridge
services:
  tinkoffinvest.web:
    image: tinkoffinvest.web
    build:
      context: .
      dockerfile: TinkoffInvest/src/TinkoffInvest.Web/Dockerfile
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: "tinkoff_invest"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - t-network

  seq:
    container_name: seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
    networks:
      - t-network
volumes:
  postgres-data:
